/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountdownTimer: typeof import('./../src/components/CountdownTimer/index.vue')['default'];
    CustomHeader: typeof import('./../src/components/CustomHeader/index.vue')['default'];
    CustomInput: typeof import('./../src/components/CustomInput/index.vue')['default'];
    CustomModal: typeof import('./../src/components/CustomModal/index.vue')['default'];
    Product: typeof import('./../src/components/Product/index.vue')['default'];
    ProductItem: typeof import('./../src/components/Product/product-item.vue')['default'];
    RemainingQuantity: typeof import('./../src/components/Product/remaining-quantity.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Tabbar: typeof import('./../src/components/Tabbar/index.vue')['default'];
    VanButton: typeof import('vant/es')['Button'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanConfigProvider: typeof import('vant/es')['ConfigProvider'];
    VanField: typeof import('vant/es')['Field'];
    VanIcon: typeof import('vant/es')['Icon'];
    VanLoading: typeof import('vant/es')['Loading'];
    VanPopup: typeof import('vant/es')['Popup'];
    VanSticky: typeof import('vant/es')['Sticky'];
    VanSwipe: typeof import('vant/es')['Swipe'];
    VanSwipeItem: typeof import('vant/es')['SwipeItem'];
    VanSwitch: typeof import('vant/es')['Switch'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabbar: typeof import('vant/es')['Tabbar'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
    VanTabs: typeof import('vant/es')['Tabs'];
    VanUploader: typeof import('vant/es')['Uploader'];
  }
}
